const loginPanel = document.getElementById("login-panel");
const adminPanel = document.getElementById("admin-panel");
const loginMessage = document.getElementById("login-message");
const saveMessage = document.getElementById("save-message");
let content;
const labels = { fajr: "Fajr", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha" };
function showAdmin(data) { content = data; loginPanel.hidden = true; adminPanel.hidden = false; document.getElementById("time-fields").innerHTML = Object.entries(labels).map(([key, label]) => key === "maghrib" ? `<label class="admin-label">${label}<input value="5 minutes after sunset" disabled><small>Set automatically</small></label>` : `<label class="admin-label">${label}<input data-prayer="${key}" value="${content.iqamaTimes[key] || ""}" maxlength="30" required></label>`).join(""); document.getElementById("jumuah").value = content.jumuah || ""; [0, 1, 2].forEach((index) => { document.getElementById(`announcement-${index + 1}`).value = content.announcements[index] || ""; }); }
async function loadAdmin() { const response = await fetch("/api/admin/content", { cache: "no-store" }); if (response.ok) showAdmin(await response.json()); }
document.getElementById("login-form").addEventListener("submit", async (event) => { event.preventDefault(); loginMessage.textContent = ""; const response = await fetch("/api/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: document.getElementById("password").value }) }); if (!response.ok) { loginMessage.textContent = "Incorrect password."; return; } document.getElementById("password").value = ""; await loadAdmin(); });
document.getElementById("content-form").addEventListener("submit", async (event) => { event.preventDefault(); saveMessage.textContent = ""; const iqamaTimes = { ...Object.fromEntries([...document.querySelectorAll("[data-prayer]")].map((input) => [input.dataset.prayer, input.value.trim()])), maghrib: "5 minutes after sunset" }; const announcements = [1, 2, 3].map((index) => document.getElementById(`announcement-${index}`).value.trim()).filter(Boolean); const response = await fetch("/api/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ iqamaTimes, jumuah: document.getElementById("jumuah").value.trim(), announcements }) }); const result = await response.json(); if (!response.ok) { saveMessage.textContent = result.error || "Could not save changes."; return; } content = result; saveMessage.textContent = "Saved. The public site is updated."; });
document.getElementById("logout").addEventListener("click", async () => { await fetch("/api/logout", { method: "POST" }); adminPanel.hidden = true; loginPanel.hidden = false; });
loadAdmin();
