const schedule = { fajr: "", dhuhr: "", asr: "", maghrib: "", isha: "", jumuah: "" };
const fields = { fazar: "fajr", zohar: "dhuhr", asar: "asr", magrib: "maghrib", isha: "isha" };
const adhanKeys = { "adhan-fajr": "fajr", "adhan-dhuhr": "dhuhr", "adhan-asr": "asr", "adhan-maghrib": "maghrib", "adhan-isha": "isha" };
const phoenixParts = () => Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone: "America/Phoenix", month: "long", day: "numeric" }).formatToParts(new Date()).map(({ type, value }) => [type, value]));
function displayDate() { const now = new Date(); const readable = now.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" }); const compact = now.toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" }); const today = document.getElementById("today-date"); const scheduleDate = document.getElementById("today-date-schedule"); const year = document.getElementById("year"); const hijri = document.getElementById("hijri-date"); if (today) today.textContent = readable; if (scheduleDate) scheduleDate.textContent = compact; if (year) year.textContent = now.getFullYear(); try { if (hijri) hijri.textContent = new Intl.DateTimeFormat("en-US-u-ca-islamic", { day: "numeric", month: "long", year: "numeric" }).format(now); } catch (_) {} }
function nextIqamah() { const now = new Date(); const ordered = [["Fajr", schedule.fajr], ["Dhuhr", schedule.dhuhr], ["Asr", schedule.asr], ["Maghrib", schedule.maghrib], ["Isha", schedule.isha]]; const next = ordered.find(([, time]) => { const value = Date.parse(`January 1, 2020 ${time}`); if (Number.isNaN(value)) return false; const then = new Date(value); return then.getHours() * 60 + then.getMinutes() > now.getHours() * 60 + now.getMinutes(); }) || ordered[0]; const target = document.getElementById("next-iqamah"); if (target) target.textContent = next[1] ? `${next[0]} · ${next[1]}` : "Please check the schedule"; }
async function getContent() { const response = await fetch("/api/content"); if (!response.ok) throw new Error("Admin API unavailable"); return response.json(); }
async function loadHomeSchedule() { let content; try { content = await getContent(); } catch (_) { content = await fetch("files/site-content.json").then((response) => response.json()); } Object.assign(schedule, content.iqamaTimes, { jumuah: content.jumuah || "" }); Object.entries(fields).forEach(([id, key]) => document.getElementById(id).textContent = schedule[key] || "Check announcements"); if (schedule.jumuah) document.getElementById("jumuah").textContent = schedule.jumuah; const announcement = document.getElementById("announcement-text"); if (announcement) announcement.textContent = (content.announcements || []).join(" • ") || "No announcements at this time."; nextIqamah(); try { const monthlySchedule = await fetch("files/adhan-schedule.json").then((response) => response.json()); const today = phoenixParts(); const day = (monthlySchedule[today.month] || []).find((entry) => Number(entry.day) === Number(today.day)); Object.entries(adhanKeys).forEach(([id, key]) => document.getElementById(id).textContent = day?.[key] || "—"); } catch (_) {} }
displayDate(); if (document.getElementById("fazar")) loadHomeSchedule().catch(() => { const target = document.getElementById("next-iqamah"); if (target) target.textContent = "Schedule unavailable"; }); const menuButton = document.querySelector(".menu-toggle"); if (menuButton) menuButton.addEventListener("click", () => { const nav = document.querySelector(".main-nav"); const isOpen = nav.classList.toggle("open"); menuButton.setAttribute("aria-expanded", isOpen); });
