const schedule = { fajr: "", dhuhr: "", asr: "", maghrib: "", isha: "", jumuah: "" };
const fields = { fazar: "fajr", zohar: "dhuhr", asar: "asr", magrib: "maghrib", isha: "isha" };
const adhanFields = { "adhan-fajr": "adhanFajr", "adhan-dhuhr": "adhanDhuhr", "adhan-asr": "adhanAsr", "adhan-maghrib": "adhanMaghrib", "adhan-isha": "adhanIsha" };
const adhanKeys = { "adhan-fajr": "fajr", "adhan-dhuhr": "dhuhr", "adhan-asr": "asr", "adhan-maghrib": "maghrib", "adhan-isha": "isha" };
const phoenixParts = () => Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone: "America/Phoenix", month: "long", day: "numeric" }).formatToParts(new Date()).map(({ type, value }) => [type, value]));
function displayDate() { const now = new Date(); const readable = now.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" }); const compact = now.toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" }); const today = document.getElementById("today-date"); const scheduleDate = document.getElementById("today-date-schedule"); const year = document.getElementById("year"); const hijri = document.getElementById("hijri-date"); if (today) today.textContent = readable; if (scheduleDate) scheduleDate.textContent = compact; if (year) year.textContent = now.getFullYear(); try { if (hijri) hijri.textContent = new Intl.DateTimeFormat("en-US-u-ca-islamic", { day: "numeric", month: "long", year: "numeric" }).format(now); } catch (_) {} }
function nextIqamah() { const now = new Date(); const ordered = [["Fajr", schedule.fajr], ["Dhuhr", schedule.dhuhr], ["Asr", schedule.asr], ["Maghrib", schedule.maghrib], ["Isha", schedule.isha]]; const next = ordered.find(([, time]) => { const value = Date.parse(`January 1, 2020 ${time}`); if (Number.isNaN(value)) return false; const then = new Date(value); return then.getHours() * 60 + then.getMinutes() > now.getHours() * 60 + now.getMinutes(); }) || ordered[0]; document.getElementById("next-iqamah").textContent = next[1] ? `${next[0]} · ${next[1]}` : "Please check the schedule"; }
if (document.getElementById("fazar")) fetch("files/prayertime.json").then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { schedule.fajr = data.fazar || ""; schedule.dhuhr = data.zohar || ""; schedule.asr = data.asar || ""; schedule.maghrib = data.magrib || ""; schedule.isha = data.isha || ""; schedule.jumuah = data.jumuah || ""; Object.entries(fields).forEach(([id, key]) => document.getElementById(id).textContent = schedule[key] || "Check announcements"); if (schedule.jumuah) document.getElementById("jumuah").textContent = schedule.jumuah; nextIqamah(); return fetch("files/adhan-schedule.json"); }).then((response) => response.ok ? response.json() : Promise.reject()).then((monthlySchedule) => { const today = phoenixParts(); const day = (monthlySchedule[today.month] || []).find((entry) => Number(entry.day) === Number(today.day)); Object.entries(adhanKeys).forEach(([id, key]) => document.getElementById(id).textContent = day?.[key] || "—"); }).catch(() => { document.getElementById("next-iqamah").textContent = "Schedule unavailable"; });
displayDate(); const menuButton = document.querySelector(".menu-toggle"); if (menuButton) menuButton.addEventListener("click", () => { const nav = document.querySelector(".main-nav"); const isOpen = nav.classList.toggle("open"); menuButton.setAttribute("aria-expanded", isOpen); });
